# Generated by Django 4.2.7 on 2024-03-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmodel",
            name="weight",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="postbox",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="postoffice",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
