# Generated by Django 4.2.7 on 2023-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='mini_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
