# Generated by Django 4.2.7 on 2024-01-22 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_itemimagemodel_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimagemodel',
            name='product_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='shop.categorymodel'),
        ),
    ]
