# Generated by Django 4.2.7 on 2024-01-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_categoryimagemodel_product_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmodel',
            old_name='starts',
            new_name='stars',
        ),
    ]
