# Generated by Django 4.2.7 on 2023-12-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopcontactsmodel_itemmodel_mini_image_ordermodel'),
        ('shop', '0003_shopcontactsmodel'),
    ]

    operations = [
    ]
