# Generated by Django 4.2.7 on 2024-01-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_rename_starts_itemmodel_stars"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quantity product"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.itemmodel"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.ordermodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="items",
            field=models.ManyToManyField(
                through="shop.OrderItemModel", to="shop.itemmodel"
            ),
        ),
    ]
