# Generated by Django 4.2.7 on 2023-12-20 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_ordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(max_length=30)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update')),
                ('rate_by_stars', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='rate by stars')),
                ('item_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='shop.itemmodel')),
            ],
        ),
    ]
