# Generated by Django 4.2.7 on 2023-12-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='state',
            field=models.CharField(choices=[('pending', 'в очікуванні'), ('visible', 'видимий'), ('invisible', 'невидимий')], default='pending', max_length=10),
        ),
    ]
