# Generated by Django 4.2.7 on 2024-01-30 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_orderitemmodel_ordermodel_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="item_set",
        ),
    ]
