# Generated by Django 4.2.7 on 2024-01-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewModel',
        ),
    ]
