# Generated by Django 4.2.7 on 2024-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_review_reviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='stock',
            field=models.CharField(choices=[('pending', 'в очікуванні'), ('visible', 'видимий'), ('invisible', 'невидимий')], default='IN_STOCK', max_length=40),
        ),
    ]
