# Generated by Django 4.2.7 on 2024-01-30 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_remove_ordermodel_item_set"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="items",
            new_name="item_set",
        ),
    ]
