# Generated by Django 4.2.7 on 2024-01-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_itemmodel_in_stock_itemmodel_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='stock',
            field=models.CharField(choices=[('IN_STOCK', 'В наявносі'), ('OUT_OF_STOCK', 'Немає в наявності'), ('BACKORDER', 'Очікується'), ('SPECIFIC_ORDER', 'Під замовлення')], default='IN_STOCK', max_length=40),
        ),
    ]
