# Generated by Django 4.2.7 on 2023-12-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_ordermodel_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='items',
            new_name='item_set',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
