# Generated by Django 4.2.7 on 2024-01-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_itemmodel_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='visits',
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='ItemStatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.BigIntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='shop.itemmodel')),
            ],
        ),
    ]
