# Generated by Django 4.2.7 on 2024-03-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_ordermodel_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="acq_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID еквайера"
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("None", "Не оплачено"),
                    ("error", "error"),
                    ("liqpay", "Liqpay"),
                ],
                default="None",
                max_length=50,
            ),
        ),
    ]
