# Generated by Django 4.2.7 on 2024-02-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_novapost_ordermodel_nova_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopcontactsmodel",
            name="sender_address",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shopcontactsmodel",
            name="sender_warehouse_index",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
