# Generated by Django 4.2.7 on 2024-01-19 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_itemmodel_visits_alter_itemmodel_id_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='item_set',
            new_name='item',
        ),
    ]
