# Generated by Django 4.2.7 on 2024-03-03 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_ordermodel_acq_id_alter_ordermodel_payment_status"),
        ("shop", "0009_shopcontactsmodel_sender_address_and_more"),
    ]

    operations = []
