# Generated by Django 4.2.7 on 2024-01-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_item_set_reviewmodel_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='rate_by_stars',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='stars'),
        ),
    ]
