# Generated by Django 4.2.7 on 2024-03-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_merge_20240303_0948"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novapost",
            name="cost_on_site",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
